### PR TITLE
Add special transformation matrices to HLSL++

### LINKED ISSUE #10: Add functions to create projection matrices
Add options like different ndcs, handedness, etc.

### PR DESCRIPTION
**Pull request by egorodet**
- Add static functions for matrix types to create transformations (enabled with macro-definition `HLSLPP_FEATURE_TRANSFORM`):
  - Scale, translation and rotation matrices for `float2x2`, `float3x3` and `float4x4` m
  - World to view `look at` coordinates transformation matrix `float4x4`
  - View to projection `orthographic` and `perspective` coordinates transformation `float4x4` matrices (closed #10)
- Print test failures to error output additionally to debug `assert` to make errors visible in Release builds

### CODE REVIEW

**Comment by redorav** [comment]
Hi @egorodet, thank you for your contribution and your interest in the library, that's a lengthy pull request. I have gone through all the changes and here are a couple of observations with regards to the PR methodology.

· PR needs to ideally be a single commit for a single feature. I would accept maybe a couple, but you have 18 and it's not clear what the "final" changes really are and I have to go back and forth making sure
· Needs to work on all advertised platforms. As it is, both Android versions don't compile. I have a feeling it's due to including <cmath> but I'd have to dive deeper. In that case it may be better to use cosf/sinf as they'd probably be more widely available (even if not as "nice" or "clean" as the std:: version)

As for the actual content the contributions seem to be:
	1) Functions to compute orthographic, perspective and view matrices
	2) Functions to scale, translate, and rotate
	3) Implicit bool conversion from vector
	
I'll comment on each of these.

1) In terms of the projection matrix code, I like that you're trying to cater for some variation (e.g. via left_handed and zclip_zero). They still fail to capture some of the subtleties of the different graphics APIs they may be used for, e.g. which direction y runs in (-1 top, +1 bottom or viceversa) or options one might want such as infinite z plane, etc. so they could do with some improvement in that area. I already had some code for it but I haven't finished it.

The way I was designing it was to have a struct ProjectionParams that encapsulates the necessary parameters and has several constructors that can take different arguments, but have a single point where we actually build the matrix. The use would be something like

float4x4 myPerspectiveMatrix = float4x4::perspective(ProjectionParams(near, far, ...));

With regards to the lookat function it looks fine and I don't have too many comments, other than what I'll mention in the next point.

2) In terms of the transform functions, I am not super keen on adding them as they assume a specific logical layout. This is the eternal war between logical "row-major" and "column-major" and I don't want hlsl++ to be one or the other. In physical terms (what you call storage), the matrices are indeed laid as rows but a user can actually use them as columns throughout their code if they like. Hlsl/DirectX don't assume anything about your logical matrices (and the storage can be changed in the compiler shader-wide), so I don't want to either. However functions such as translate assume the position is in the last row.

Would it be helpful to you if I add an optional extra include (e.g. hlslpp_user.h) that allows you to extend and add as much extra code as you like at the end of hlsl++.h? Transform code is relatively simple to implement on top of hlsl++, and you can add it to the hlslpp namespace if that's how you would like to be as well.

Just for a bit of context, I'll mention that once upon a time I had something like a HLSLPP_STORAGE_ROW_MAJOR and HLSLPP_STORAGE_COLUMN_MAJOR define, and I tried to have functions change behavior based on that, because I wanted users to not have to transpose. I eventually removed it as it was promising to add a ton of complexity and hlslpp can already do pre and post multiplication so that the user can opt in to whatever they like (in terms of logical majorness). I have looked at the existing code, and I think the only place where I violate this rule is the quaternion, which builds a rotation matrix (and I should probably fix it!)

For the sake of the perspective and view matrices, we could have a flag or similar for majorness and make sure we build it appropriately based on that. It means that future additions or improvements need to take it into account. I am willing to make exceptions here because the code is complex and has many pitfalls for normal users but small enough that I can afford to maintain and fix it.

3) With regards to the implicit conversion to bool I'm afraid I'm going to have to say no. You can already express what you want via any() and all() and that is the correct way to do it. Someone else could argue that if(myVector) means "if any component is not zero" as that statement is itself ambiguous. I'm also not a huge fan of implicit conversions (i.e. allowing a float4 into a function that takes a bool)

Let me know what you think and we can have further discussion. I don't want you to feel like I'm being difficult, as by all means I'm quite happy about you integrating it into Methane, but I don't want to cater to only some users.

**Comment by egorodet** [comment]
Hi @redorav, you can review final changes in pull request (PR) on the "Files Changed" tab without going through all commits. Also the number of commits in PR should not be an issue since GitHub provides [squash and merge option](https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/about-pull-request-merges#squash-and-merge-your-pull-request-commits) which creates only one commit after PR merge.

I can fix broken build for Android, but currently I don't have Android toolchain installed. It would be useful to have continuous integration system set for your project for all supported platforms to simplify future merges.

I understand your intention to make the math library independent from row-major or column-major layout and I like it in general. Unfortunately users still need to keep in mind actual layout of data in CPU memory to correctly map it to the GPU memory read from shaders in case if vectors or matrices are written to GPU uniform/constant buffers. When I started using HLSL++ I spent some time to learn the library internals to understand an actual data layout, because it was not specified anywhere in readme, code or comments. I think that it is better to mention physical data layout explicitly than not saying anything at all. Of course logical data layout in matrices could be different, but in general you should know both to make things work correctly.

I've added primitive transformation matrices for scale/translate/rotate because I think that it is essential to have them ready out of the box to enable using the library right away. While most of these matrices are quite simple, the rotation around a given axis is more complex and it also has to provide consistent results with primitive rotations around coordinate axes. I've explicitly specified in comment that current implementation is written for left-vector to right-matrix multiplication in row-major order. Probably it would be better to add this specification to function names too and extend it with other variations in future (maybe using template arguments). This PR could be considered as a starting point for future work.

Let me explain why I've separated functions for creating transformation matrices from the matrix types, instead of using static methods of structs. I've thought about existing headers as a core of math library implementing the documented HLSL math features and transformation matrices as a kind of utility or extension. So I've put these functions to a separate header. Probably it should not be included in the root header hlsl++.h, but be made available as an optional header, which can be included by users when transformations are actually needed. This would minimise the amount of compiled code.

I do not insist on explicit conversion of vectors to bool and agree with your arguments. The reason why I've added this conversion is to fix vectors comparison in my unit tests based on Catch2 macros `CHECK(v1 == v2);`. I will try to fix it in some other way.

I am totally fine if you believe that changes proposed in this Pull Request are not quite right for your library. I already have all of these changes in my forked repository and can use them in my project from that fork. If you still think that some of these changes are useful for merging back to root repository, please let me know what I should fix (besides broken Android build) to make it happen.

**Comment by redorav** [comment]
Hi @egorodet, thanks a lot for the amount of work you're putting into the PR. I've looked at the latest code and I think this looks pretty good, I certainly wasn't expecting it. I think the majorness changes make it a lot more attractive to users to use the transform extension and for me to put it in. The changes to the extensibility of the perspective and orthographic functions are pretty good too. I have a few bits of feedback that I think we can discuss to take this to a level that I think we could integrate.

1) I like what you've done with the perspective and orthographic matrix, I have a few changes of my own that extend the functionality, but I'm thinking that I'll try to integrate them with yours once this goes in. The fact that it's a struct lends itself well to modifying without affecting other users. Just for a heads up, I was planning to add these as well to that structure.

	bool reverseDepth; // Far depth 0, near depth 1
	bool infiniteDepth; // No z plane
	bool invertY; // If enabled Y runs from -1 at the top to 1 at the bottom

2) Just a minor tweak to some naming, zclip_zero -> zClipZero

3) I really like that you've gone in and done the ColumnMajor vs RowMajor stuff, really sells this to me to be honest. I've noticed that only translation matrices have it, rotation matrices probably need it too, only scale are symmetrical.

4) I'm not quite sure how to best do the majorness selection, I think there need to be several options we can discuss.

	a) Hardcode the majorness. For fast debug builds we probably want to have it on by default, most people would only use one or the other, then one can enable the dynamic option via HLSLPP_LOGICAL_LAYOUT_DYNAMIC. In a Release build of course everything gets optimized in dynamic selection, but at least the option is there.
	b) We need to be able to change the default layout regardless of whether it's dynamic or fixed, otherwise setting it every time can be a pain and a source of errors. So something like #define HLSLPP_LOGICAL_LAYOUT_DEFAULT HLSLPP_LOGICAL_LAYOUT_ROW_MAJOR which defaults to ROW_MAJOR if nothing is defined
	c) Probably the simplest way to do the above for is to have a member inside MatrixLayout that lets you define the DefaultLayout. What this means is that all default parameters are MatrixLayout layout = MatrixLayout::DefaultLayout.

enum class MatrixLayout
{
	RowMajor,
	ColumnMajor,
#if HLSLPP_LOGICAL_LAYOUT_DEFAULT == HLSLPP_LOGICAL_LAYOUT_ROW_MAJOR
	DefaultLayout = RowMajor
#else
	DefaultLayout = ColumnMajor
#endif
}

	Anyway, all that is if you think there's any merit to having it selected at runtime. There probably really isn't a compelling reason to do it to be honest, and we can simplify the code. If need be we can add it later.
	
5) I'm still not sold on the C-like naming of the functions such as float4x4_perspective. I would expect something like float2x2::scale(2.0f, 0.0f, 0.0f, 2.0f), and the equivalent for 3x3. I actually don't mind if you want to do a more "intrusive" integration behind a define or something like that, meaning that functions become:

	float4x4::perspective()
	float4x4::orthographic()
	float2x2::scale()
	float3x3::translation() -> notice how this changes from translate to translation. This is because translate is a verb, but this only returns a matrix that will do the translation, it doesn't translate anything itself
	float3x3::rotation() -> same as before	
	float3x3::rotationx
	float3x3::rotationy
	float3x3::rotationz	
	float3x3::lookat()
	float3x3::rotateaxis
	
Notice how I removed the underscores, as none of the other public-facing functions have them (like axisangle, isinf, isfinite, etc). Naming is hard and it can look uglier :(, but I'd like to at least keep it consistent with the rest of the functions. I think the syntax here is much cleaner even if the integration needs to be tighter. I actually don't mind if you want to have a sort of HLSLPP_FEATURE_TRANSFORM define and then in each class you add the include. It's just going to be 3 files anyway. Something like this:

struct float3x3
{
	[existing code]

	#include "hlsl++_transform_3x3.h"
}

hlsl++_transform_3x3.h

#if defined(HLSLPP_FEATURE_TRANSFORM)

hlslpp_inline float3x3 float3x3::scale(float sx, float sy, float sz = 1.f)
{
	return float3x3(
		sx,  0.f, 0.f,
		0.f, sy,  0.f,
		0.f, 0.f, sz
	);
}

#endif

I'll leave the final form up to you, or I can always shuffle it around a bit later.

6) I noticed that in your latest commit you removed orthographic() and perspective(), if you want to unify them that's fine, but also creating an alias to those two functions would be quite useful, I think.

7) There are some minor things that I've noticed that you may want to optimize in terms of performance, like for instance there's a lot of extracting components out of the vectors and operating scalarly, then putting back that could be avoided. All the operations here probably want to use the _hlslpp_shuf intrinsics, but maybe I can make a pass over these after it has been promoted.

return float4x4
(
	v1.x + c,    v2.x + as.z, v2.z - as.y, 0.f,
	v2.x - as.z, v1.y + c,    v2.y + as.x, 0.f,
	v2.z + as.y, v2.y - as.x, v1.z + c,    0.f,
	0.f,         0.f,         0.f,         1.f
);

8) Just a minor last thing, I never use the 0.f notation, I find it clearer to do 0.0f, 1.0f, etc always so that should be an easy find + replace :)

**Comment by egorodet** [comment]
Short summary of the latest changes:
- Removed operators casting vectors to bool
- Attempted to fix Android build by using pure C functions `cosf`, `sinf`, `printf`. I was not able to build Android locally because of some strange VS project build error which is blocking the code compilation. Please try it on your side and let me know if there are more build errors.
- Added support for generation of both Row-major an Column-major matrix layout for `translation`, `look_at` and `projection` transformations using `MatrixLayout` enum argument defaulted to `RowMajor` value.
- Added `Coordinates` enum, `ZClip` enum, `ProjectionType` enum, `Frustrum` struct, `ProjectionSettings` struct and merged `float4x4_orthographic` and `float4x4_perspective` function into one function `float4x4_projection`.
- Converted `hlsl++_matrix_transform_ext.h` to optional extension header by removing it from the root header `hlsl++.h` so that it can be additionally included when it is actually needed, but do not compile along with core functions from `hlsl++.h`.

You've already reviewed all of them while I was writing this summary 👍🏻

**Comment by redorav** [comment]
I can confirm that both Android builds work now

**Comment by egorodet** [comment]
Thank you @redorav, for fast and detailed review of the latest changes! I will try to address your requests a little bit later.

**Comment by egorodet** [comment]
@redorav, could you please clarify code naming convention? From what I see in existing source code of the library:
- struct names: `lowerCamelCase`
- variable and member names: `lower_snake_case`
- function names: `lower_snake_case`

These contradicts with the naming changes you propose:
- You propose to rename `zclip_zero -> zClipZero` (and provided some other examples of `lowerCamelCase` for members of structs), but other struct members in your library are named in `lower_snake_case`
- You propose to name static functions `rotationx`, `rotationaxis`, but there are many other functions in the library named in `lower_snake_case`. Writing names all in lower case without any word separators or case change separators is not good for code readability.
- The naming of new structs like `ProjectionSettings` and enum types `MatrixLayout` also seems to be inconsistent with current style used in library. Should they be renamed to `projectionSettings` and `matrixLayout`?

Please clarify the coding style I should use.

**Comment by egorodet** [comment]
@redorav I've tried to address most part of your comments (numbering is matching original issue numbers):
1. I prefer to leave additional options for the future to focus on issues of the current implementation. You can implement additional projection settings when the pull request is merged.
2. Fixed members naming as you proposed `zclip_zero -> zClipZero`, but now it looks inconsistent with other members naming in vector and matrix types (see my previous question regarding naming convention).
3. Fixed rotation matrices generation depending on selected layout and coordinate system. It affects only the direction of rotation, but it is still important.
4. Fixed with the simplest solution for now: to hardcode the metric layout and coordinate system with macro-definitions in compile time: `HLSLPP_LOGICAL_LAYOUT` and `HLSLPP_COORDINATES` are defined in `transform/hlsl++_transform_common.h`. Changing this parameters in runtime can be implemented by request in future, if it is really needed.
5. Fixed naming of tranformation functions by putting them inside of matrix types as you proposed, but I'm still not sure what functions naming style to choose for consistency with the rest of the library: `rotation_axis` or `rotationaxis` or `rotationAxis` (see my previous question regarding naming convention)?
6. Fixed with reverting back to separate functions for `orthographic()` and `perspective()` to keep them as simple as possible.

**Comment by redorav** [comment]
@egorodet thanks for taking the time to address all these. Here's the latest feedback. I think we're quite close to having something ready.

1) That's fair enough, we can always extend it later, it looks good as it is. It will also be a good idea to be able to modify the default for projection matrices as a global switch, but that can come later

2) I think you're right with regards to the notation and code conventions, I've never really had this naming convention as a rule in other projects I work on locally, but in trying to get the publicly facing hlsl++ as close to the hlsl syntax as possible I have ended up with a mostly lowercase and snake case code style. I think you're right that we should respect what's already there so disregard my comment about the camelCase and let's make structs, functions and variable names lowercase as was your original idea. Sorry for going back and forth on this. This also applies for example then to frustum and projection settings

3) I really like the way you've done this, means a lot less code, easier to read and modify as well

4) Also +1, I think the simplest was to hardcode, seems to me like using both is a bit of an edge case, if someone needs it at some point we can always revisit

5) In terms of the naming convention I refer to point 2, I think you're right that it definitely should not be camelCase, whether to have underscores or not I would say now it's up to you. I think rotation_axis which I think is what you favor is perfectly fine.

6) Ok from me in terms of splitting into two functions orthographic and perspective, I think I'd also rather have it that way. There is another minor thing I want to point out with regards to the naming of the variables internally, if we are to assume row major as default, the naming of the m variables should be m[row][column], so variable m23 should be m32

7) Excellent

Another thing I should mention is that when I added Linux and Mac, I broke AppVeyor and it was silently "passing" but not really compiling, I spent a bit of time today fixing it. One of the more esoteric builds (MSVC ARM) is still failing but hopefully it won't take long. I'll accept the PR anyway and deal with any fallout.

One last thing I'll have to add when it's all in is update the documentation to reflect the new functionality

**Comment by egorodet** [comment]
Great! I will make the final fixes tomorrow. MacOS and Linux should build fine at least for code in 'include' dir, because it already builds fine as a part of [Methane Kit CI](https://egorodet.visualstudio.com/MethaneKit/_build/results?buildId=1186&view=results).

**Comment by redorav** [comment]
Sorry, I meant that when I added Linux and MacOS, I broke the Windows builds (because I implicitly disabled how AppVeyor does things). It's all good and fixed now.

Since you're writing your own rendering framework I have added it to a list I created just a couple of days ago, maybe you're interested. It's a list of engines/frameworks for graphics/game development. Maybe you'll find it useful. https://github.com/redorav/public_source_engines

**Comment by egorodet** [comment]
Hi @redorav, now all review fixes should be in place. Also I've added one line to `Readme.md` describing the transformations feature - please check if it is written well. I see that AppVeyor build fails for VS 2019 Android ARM - I was not able to build it locally too, so hope that it is not my issue.

**Comment by egorodet** [comment]
Hi @redorav, It seems that I've fixed weird clang compiler error in Android ARM build configuration. It seems to be a compiler bug that was somehow related to extracting vector components from the result of vectors cross in `look_at` matrix. Simply adding multiplication of vectors cross by `1.f` has fixed this failure. I've added this workaround specifically for Android ARM build configuration, other configurations build normally without it.

Could you please take a look at the latest changes?

**Comment by redorav** [comment]
@egorodet, sorry for the delay. I have reviewed the last commits and have some last very small comments on it. Once those are done I'll push the green button.

1) I just noticed that you renamed left, right, top, etc. to x_left, x_right... I don't think that's really necessary and would be cleaner without.
2) I managed to repro the Android issue but I don't really like the hack you've had to do. However, I propose a different one that I have tested working, where you build 4 float4 instead of a big matrix with floats like you do in the row major version. It has the advantage that the vectors are never turned to float but always kept as vectors (float1). I'd rather have that.

I can now see how squash and merge is supposed to work. If you would like to write the commit message for the total amount of changes that you've put in the PR, I'll just copy and paste it and we can consider this as good as done. I'll probably rework some of the implementations in the coming days when I find time and see if I can make them better but this shouldn't affect the interface. Overall I really like the quality of the work you've put into this, so thank you.

**Comment by egorodet** [comment]
1. I had to rename members of `frustrum` struct (specifically `near` and `far`) because I got build errors with original names in my project likely because of some macro-definitions with the same names used in some external headers. I did not find exactly what defines or headers causing this collision, so the best way to fix it was renaming. Will try to look at it once again.
2. Could you provide an example of code for your workaround?

Possible commit message is already available in the description of the Pull Request at the top of this page. You may modify it if needed.

**Comment by redorav** [comment]
@egorodet 

1) I think I know what you mean, windows.h defines near and far for legacy reasons and it always bites me every now and again. Would it be better/clearer to do near_plane and far_plane instead?

Look here https://stackoverflow.com/questions/3046964/define-far-define-near-windef-h

2) The code I used was the following, which was the simplest change possible to the existing.
return float4x4(
		float4(right.x,               up_dir.x,               look.x,               0.0f),
		float4(right.y,               up_dir.y,               look.y,               0.0f),
		float4(right.z,               up_dir.z,               look.z,               0.0f),
		float4(-dot(position, right), -dot(position, up_dir), -dot(position, look), 1.0f)
	);

**Comment by egorodet** [comment]
1. Do you mean to rename only near/far to planes or other members of frustrum too? I'm not sure that it will look better than current version with _plane suffix for all members (which is quite lengthy when used in code).
2. I will apply your workaround - it is definitely better.

**Comment by redorav** [comment]
1) Ok fair enough, how about near_z and far_z? Basically for me it's a lot more intuitive to start typing left, right, top, bottom, near and far given all the existing literature than begin with x, y or z. Autocomplete can do the rest.

**Comment by egorodet** [comment]
Another solution to fight Windows defines could be to add this macroses prior frustrum struct definition:
```cpp
#ifdef near
#undef near
#endif

// the same for far
```

**Comment by egorodet** [comment]
Yeah, sure I can move coordinates to the back, no problem.

**Comment by redorav** [comment]
@egorodet actually I don't dislike the undef solution at all

**Comment by egorodet** [comment]
I've tried to undef near/far defines, but got build errors in my project from DirectX headers. It appeared that near/far defines are actually used by `DEFINE_GUID(...)` macro broadly used in DirectX haders. So I had to fall back to renaming of frustrum members as we agreed.

**Comment by redorav** [comment]
That's annoying. I've tried looking at what other people do but everyone just has near and far, seems like no one has included the windows headers alongside their projection functions :(

I explored the possibility of using push_macro and pop_macro but that only fixes the problem in the struct, anytime you want to actually use it, the same issue reappears.

Can I ask one last tiny thing? It really bothers me to see left_x and top_y for some reason, in my mind that doesn't make a lot of sense as I already know that goes in the x and y, just like we don't have width_x and height_y. If we absolutely must have it in near and far I would rather only they have the suffix. It's just that bit of inconsistency we'll have to live with for Windows' sake.

If you are able to do that in the next few hours I'll probably merge right away.

**Comment by egorodet** [comment]
I've also noticed that some other libraries still use `near` and `far` naming. That would require their users to solve the problem with headers include order, which also could be very annoying.

**Pull request merged**
